name: Build Frontend
on: 
  push:
    branches: [main]

jobs:
  build-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: initialize node
        uses: actions/setup-node@v4
        
      - name: Install Node
        run : npm install
        
      - name: Build Frontend
        run : npm run build