name: Node Setup
on: 
  push:
    branches: [main]

jobs:
  node-setup-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@4

      - name: initialize node
        uses: actions/setup-node@4
      
